repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.5.0 # https://github.com/pre-commit/pre-commit-hooks/releases
  hooks:
    - id: trailing-whitespace
    - id: no-commit-to-branch
    # - id: ...
- repo: https://github.com/lorenzwalthert/precommit
  rev: v0.3.2
  hooks:
  - id: parsable-R
  - id: use-tidy-description
  - id: roxygenize
  # - id: ...
